services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
        - "8000:8000"
    environment:
        - IS_PERSISTENT=TRUE
        - CHROMA_DB_IMPL=duckdb
    restart: unless-stopped